/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cooperativa.cooperativa.igu;

import com.cooperativa.cooperativa.servicio.CuentaServicio;
import com.cooperativa.cooperativa.control.Cuenta;
import java.awt.Component;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author godofredo
 */
public class frmCuentas extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    String encabezados[] = {"Id", "Codigo", "Nombre", "Tipo", "Naturaleza", "Clasificacion",
        "Nivel", "Activa"
    };
    CuentaServicio control = new CuentaServicio();

    public frmCuentas() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo.setColumnIdentifiers(encabezados);
        tblCuentas.setModel(modelo);
        cargarCuentas();
        ajustarColumnas(tblCuentas);

    }

    public void cargarCuentas() {
        List<Cuenta> cuentas = control.verCuentas();
        for (Cuenta cuenta : cuentas) {
            modelo.addRow(new Object[]{
                cuenta.getId(), cuenta.getCodigo(), cuenta.getNombre(), cuenta.getTipo(),
                cuenta.getNaturaleza(), cuenta.getClasificacion(), cuenta.getNivel(), cuenta.getActiva()
            });
            tblCuentas.setModel(modelo);
        }
    }

    public static void ajustarColumnas(JTable tabla) {
        for (int col = 0; col < tabla.getColumnCount(); col++) {
            int maxAncho = 0;

            // Medir el encabezado
            TableColumn columna = tabla.getColumnModel().getColumn(col);
            TableCellRenderer headerRenderer = tabla.getTableHeader().getDefaultRenderer();
            Component headerComp = headerRenderer.getTableCellRendererComponent(
                    tabla, columna.getHeaderValue(), false, false, 0, col
            );
            maxAncho = headerComp.getPreferredSize().width;

            // Medir cada celda
            for (int fila = 0; fila < tabla.getRowCount(); fila++) {
                TableCellRenderer renderer = tabla.getCellRenderer(fila, col);
                Component comp = tabla.prepareRenderer(renderer, fila, col);
                int ancho = comp.getPreferredSize().width + 10; // margen
                maxAncho = Math.max(maxAncho, ancho);
            }

            columna.setPreferredWidth(maxAncho);
        }

        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngFiltro = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuentas = new javax.swing.JTable();
        rbtnPatrimonio = new javax.swing.JRadioButton();
        rbtnGasto = new javax.swing.JRadioButton();
        rbtnIngreso = new javax.swing.JRadioButton();
        rbtnActivo = new javax.swing.JRadioButton();
        rbtnPasivo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(tblCuentas);

        btngFiltro.add(rbtnPatrimonio);
        rbtnPatrimonio.setText("Patrimonio");
        rbtnPatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPatrimonioActionPerformed(evt);
            }
        });

        btngFiltro.add(rbtnGasto);
        rbtnGasto.setText("Gasto");
        rbtnGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGastoActionPerformed(evt);
            }
        });

        btngFiltro.add(rbtnIngreso);
        rbtnIngreso.setText("Ingreso");
        rbtnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnIngresoActionPerformed(evt);
            }
        });

        btngFiltro.add(rbtnActivo);
        rbtnActivo.setText("Activo");
        rbtnActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnActivoActionPerformed(evt);
            }
        });

        btngFiltro.add(rbtnPasivo);
        rbtnPasivo.setText("Pasivo");
        rbtnPasivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPasivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(rbtnIngreso)
                        .addGap(79, 79, 79)
                        .addComponent(rbtnGasto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(rbtnPasivo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(rbtnActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(480, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnPatrimonio)
                    .addComponent(rbtnPasivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnGasto)
                    .addComponent(rbtnIngreso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(rbtnActivo)
                    .addContainerGap(422, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnPatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPatrimonioActionPerformed
        modelo.setRowCount(0);
        List<Cuenta> patrimonio = control.cuentasTipo("Patrimonio");
        llenarTabla(patrimonio, modelo);


    }//GEN-LAST:event_rbtnPatrimonioActionPerformed

    public void llenarTabla(List<Cuenta> datos, DefaultTableModel modelo) {
        for (Cuenta cuenta : datos) {
            modelo.addRow(new Object[]{
                cuenta.getId(), cuenta.getCodigo(), cuenta.getNombre(), cuenta.getTipo(),
                cuenta.getNaturaleza(), cuenta.getClasificacion(), cuenta.getNivel(), cuenta.getActiva()
            });
            tblCuentas.setModel(modelo);
        }
    }

    private void rbtnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnIngresoActionPerformed
        modelo.setRowCount(0);
        List<Cuenta> ingreso = control.cuentasTipo("Ingreso");
        llenarTabla(ingreso, modelo);
    }//GEN-LAST:event_rbtnIngresoActionPerformed

    private void rbtnActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnActivoActionPerformed
        modelo.setRowCount(0);
        List<Cuenta> activo = control.cuentasTipo("Activo");
        llenarTabla(activo, modelo);
    }//GEN-LAST:event_rbtnActivoActionPerformed

    private void rbtnPasivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPasivoActionPerformed
        modelo.setRowCount(0);
        List<Cuenta> pasivo = control.cuentasTipo("Pasivo");
        llenarTabla(pasivo, modelo);
    }//GEN-LAST:event_rbtnPasivoActionPerformed

    private void rbtnGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGastoActionPerformed
        modelo.setRowCount(0);
        List<Cuenta> gasto = control.cuentasTipo("Gasto");
        llenarTabla(gasto, modelo);
    }//GEN-LAST:event_rbtnGastoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnActivo;
    private javax.swing.JRadioButton rbtnGasto;
    private javax.swing.JRadioButton rbtnIngreso;
    private javax.swing.JRadioButton rbtnPasivo;
    private javax.swing.JRadioButton rbtnPatrimonio;
    private javax.swing.JTable tblCuentas;
    // End of variables declaration//GEN-END:variables
}
