/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cooperativa.cooperativa.igu;

import com.cooperativa.cooperativa.control.Periodo;
import com.cooperativa.cooperativa.servicio.PartidaServicio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author godofredo
 */

public class panelBalanzaComprobacion extends javax.swing.JPanel {

    String[] encabezados = {
        "Codigo", "Nombre de la Cuenta", "Suma Debe", "Suma Haber", "Saldo Deudor", "Saldo Acreedor"
    };
    DefaultTableModel modelo = new DefaultTableModel(encabezados, 0);
    PartidaServicio partidaserv = new PartidaServicio();
    Periodo periodo = new Periodo();

    public panelBalanzaComprobacion(Periodo periodo) {
        this.periodo = periodo;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBalanza = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBalanza = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Balanza de Comprobacion de Sumas y Saldos");

        btnBalanza.setText("Generar Balanza");
        btnBalanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanzaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tblBalanza);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBalanza, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnBalanza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBalanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanzaActionPerformed
        tblBalanza.setModel(modelo);
        cargarBalanza();
    }//GEN-LAST:event_btnBalanzaActionPerformed

    private void cargarBalanza() {
        modelo.setRowCount(0);   // limpiar tabla

        List<Object[]> filas = partidaserv.getBalanza(periodo.getId());

        double totDebe = 0, totHaber = 0;
        double totDeudor = 0, totAcreedor = 0;

        for (Object[] f : filas) {
            double sumaDebe = ((Number) f[2]).doubleValue();
            double sumaHaber = ((Number) f[3]).doubleValue();
            double saldoDeudor = ((Number) f[4]).doubleValue();
            double saldoAcreedor = ((Number) f[5]).doubleValue();

            totDebe += sumaDebe;
            totHaber += sumaHaber;
            totDeudor += saldoDeudor;
            totAcreedor += saldoAcreedor;

            modelo.addRow(new Object[]{
                f[0], // Codigo
                f[1], // Nombre
                String.format("$%,.2f", sumaDebe),
                String.format("$%,.2f", sumaHaber),
                String.format("$%,.2f", saldoDeudor),
                String.format("$%,.2f", saldoAcreedor)
            });
        }

        // Fila de totales al final
        modelo.addRow(new Object[]{
            "", "TOTALES",
            String.format("$%,.2f", totDebe),
            String.format("$%,.2f", totHaber),
            String.format("$%,.2f", totDeudor),
            String.format("$%,.2f", totAcreedor)
        });
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalanza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBalanza;
    // End of variables declaration//GEN-END:variables
}
